/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fraunhofer_ipa_kinematics_validation_KinematicsValidator */

#ifndef _Included_de_fraunhofer_ipa_kinematics_validation_KinematicsValidator
#define _Included_de_fraunhofer_ipa_kinematics_validation_KinematicsValidator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fraunhofer_ipa_kinematics_validation_KinematicsValidator
 * Method:    print
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fraunhofer_ipa_kinematics_validation_KinematicsValidator_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
