/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.composition.ui.tests;

import com.google.inject.Injector;
import de.fraunhofer.ipa.composition.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class CompositionUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("de.fraunhofer.ipa.composition.Composition");
	}

}
