/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.composition.validation;

import de.fraunhofer.ipa.kinematics.validation.KinematicsValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractCompositionValidator extends KinematicsValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.ipa.fraunhofer.de/composition"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.ipa.fraunhofer.de/kinematics"));
		return result;
	}
}
