/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GeometryAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("de/fraunhofer/ipa/geometry/parser/antlr/internal/InternalGeometry.tokens");
	}
}
