/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry.parser.antlr;

import com.google.inject.Inject;
import de.fraunhofer.ipa.geometry.parser.antlr.internal.InternalGeometryParser;
import de.fraunhofer.ipa.geometry.services.GeometryGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GeometryParser extends AbstractAntlrParser {

	@Inject
	private GeometryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGeometryParser createParser(XtextTokenStream stream) {
		return new InternalGeometryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LinkGeometry";
	}

	public GeometryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GeometryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
