/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GeometryUiModule extends AbstractGeometryUiModule {

	public GeometryUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
