/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry.ide;


/**
 * Use this class to register ide components.
 */
public class GeometryIdeModule extends AbstractGeometryIdeModule {
}
