/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fraunhofer.ipa.geometry.GeometryRuntimeModule;
import de.fraunhofer.ipa.geometry.GeometryStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GeometryIdeSetup extends GeometryStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GeometryRuntimeModule(), new GeometryIdeModule()));
	}
	
}
