/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.composition.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import de.fraunhofer.ipa.composition.CompositionRuntimeModule;
import de.fraunhofer.ipa.composition.CompositionStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CompositionIdeSetup extends CompositionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CompositionRuntimeModule(), new CompositionIdeModule()));
	}
	
}
