/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.composition.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CompositionUiModule extends AbstractCompositionUiModule {

	public CompositionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
