/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.composition.scoping;

import de.fraunhofer.ipa.kinematics.scoping.KinematicsScopeProvider;

public abstract class AbstractCompositionScopeProvider extends KinematicsScopeProvider {
}
