/*
 * generated by Xtext 2.25.0
 */
package de.fraunhofer.ipa.kinematics.validation;

import org.eclipse.xtext.validation.Check;

import urdf.RobotType;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class KinematicsValidator extends AbstractKinematicsValidator {

    private native boolean print();

	public static final String INVALID_NAME = "invalidName";


	@Check
	public void checkUniqueNames(RobotType robot) {
		if(!print()) {
			error("JNI test!", null);
		}
	}
	
	static {

        System.loadLibrary("urdf_validator");

    }
}
