/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGeometryScopeProvider extends DelegatingScopeProvider {
}
