/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.composition.parser.antlr;

import com.google.inject.Inject;
import de.fraunhofer.ipa.composition.parser.antlr.internal.InternalCompositionParser;
import de.fraunhofer.ipa.composition.services.CompositionGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CompositionParser extends AbstractAntlrParser {

	@Inject
	private CompositionGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCompositionParser createParser(XtextTokenStream stream) {
		return new InternalCompositionParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Component";
	}

	public CompositionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CompositionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
