/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.geometry;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GeometryStandaloneSetup extends GeometryStandaloneSetupGenerated {

	public static void doSetup() {
		new GeometryStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
