/*
 * generated by Xtext 2.26.0
 */
package de.fraunhofer.ipa.kinematics.formatting2;

import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import xacro.Macro;
import xacro.MacroCall;
import xacro.Parameter;
import xacro.Robot;

public class KinematicsFormatter extends AbstractJavaFormatter {

	protected void format(Robot robot, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Macro macro : robot.getMacro()) {
			doc.format(macro);
		}
		for (MacroCall macroCall : robot.getMacroCall()) {
			doc.format(macroCall);
		}
		doc.format(robot.getBody());
	}

	protected void format(Macro macro, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		for (Parameter parameter : macro.getParameter()) {
			doc.format(parameter);
		}
		doc.format(macro.getBody());
	}
	
	// TODO: implement for Parameter, ParameterPose, Body, MacroCall, ParameterCall, Joint, Link, Inertial
}
